hyoguoo/week1/boj_1000.java
hyoguoo/week1/boj_1992.java

[hyoguoo] 0주차 문제 제출

---

Kimyerim1935/프로그래머스_12948.js
Kimyerim1935/프로그래머스_82612.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/12948
- 풀이 여부: Y
- 설명: 
- 반복된 *을 출력할 때 repeat 함수를 쓰는게 좋을까요?
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/82612
- 풀이 여부: Y
- 설명
- 배열에 금액을 넣은 다음에 money에서 빼는 방식으로 코드를 짜봤는데, 다른 좋은 방법이 있을까요?

[Kimyerim1935] 1주차 문제 제출

---

hyoguoo/boj_17609.java
hyoguoo/boj_9935.java

- 문제 링크: https://www.acmicpc.net/problem/17609
- 풀이 여부: Y
- 설명
한 번 건너 뛰었는지 플래그 값을 지니고 왼쪽/오른쪽 끝에서 검사하는 방식(투포인터)로 해결했습니당  
재귀 호출한 뒤 잘린 문자열을 넣어 아래 부분에서 이미 스킵했을 경우에 대한 플래그를 함께 검사하여 return 1을 하면 더 낫지 않을까 싶네용
```java
String reverseString = getReverseString(string);
// 문자열과 문자열의 역순이 같으면 회문이므로 0 반환
if (string.equals(reverseString)) return 0;
```
- 문제 링크: https://www.acmicpc.net/problem/9935
- 풀이 여부: Y
- 설명
단순 구현 난이도로 치자면 크게 어렵지 않은 문제지만 시간 및 공간 복잡도 때문에 난이도가 높게 책정 된 문제  
include와 같은 내장 메서드로 구현하면 매번 모든 문자열을 탐색하게 되어 시간 복잡도 문제가 생기게되고,  
아래와 같이 최근 문자열을 비교하기 위해 변수에 담은 뒤 비교하면 메모리 초과(공간복잡도)가 발생하게 됩니다.  
GC 문제라고는 하는데 아직 정확히는 모르겠네여.. 해당 부분을 두 번째 코드로 수정하니 통과
1. 메모리 초과
```java
private static void popBombStrings(Stack<Character> stack, String bomb) {
StringBuilder topString = getTopString(stack, bomb);
if …
```

[hyoguoo] 1주차 문제 제출

---

soonba/boj_1213.java
soonba/boj_2164.java

- 문제 링크: https://www.acmicpc.net/problem/1213
- 풀이 여부: Y
- 설명 : 사전순서대로 계산하기 위해 문자열을 정렬 후 queue에 담아 꺼냈습니다. 다른 접근방법 고민하고 있습니다.
- 문제 링크: https://www.acmicpc.net/problem/2164
- 풀이 여부: Y
- 설명 : queue에 담아 하나꺼내 버리고, 하나 꺼내 뒤에 add하는 식으로 해결하였습니다.

[soonba] 1주차 문제 제출

---

perlpark/boj_2675.js
perlpark/boj_8958.js

- 문제 링크: https://www.acmicpc.net/problem/8958
- 풀이 여부: Y
- 설명: O일 경우 값을 1씩 증가시켜 sum에 저장하고 X를 만나면 값을 0으로 리셋해주었습니다.
- 문제 링크: https://www.acmicpc.net/problem/2675
- 풀이 여부: Y
- 설명: 문자열를 새 배열로 변환하면서 반복 메서드 repeat을 적용하고, 만들어진 새 배열을 join하여 출력했습니다.

[Perlpark] 1주차 문제 제출

---

steven/go.mod
steven/greedy/leetcode_11.go
steven/main.go
steven/string/leetcode_58.go
steven/string/leetcode_58.lengthOfLastWord.go

- 문제 링크: https://leetcode.com/problems/length-of-last-word/description/
- 풀이 여부: Y
- 설명
strings package의 strings.Fields(s)를 사용해 공백을 기준으로 한 배열 출력
```
strings.Fields("   fly me   to   the moon  ") // [fly me to the moon]
```
참고: https://pkg.go.dev/strings
- 문제 링크: https://leetcode.com/problems/container-with-most-water/description/
- 풀이 여부: Y
- 설명
처음에는 이중 for문을 사용해 풀이. Time Limit Exceeded 에러 발생 [아래 코드 참고]
```
n == height.length
2 <= n <= 10^5
```
해당 조건으로 인해 2중 for문을 사용할 시 시간복잡도는 O(n^2), 최대 10^10(100억)의 연산이 필요
결과적으로 two Pointer 방식으로 구현. 시간복잡도는 O(n).
```go
package string
func MaxArea(height []int) int {
var max int
for i := 0; i < len(height)-1; i++ {
for j := i + 1; j < len(height); j++ {
n := (j - i) * min(height[i], height[j])
if max < n {
max = n
}
}
}
return max
}
func min(a, b int) int …
```

[Steven] 1주차 문제 제출

---

perlpark/boj_10162.js
perlpark/boj_1213.js

- 문제 링크: https://www.acmicpc.net/problem/10162
- 풀이 여부: Y
- 설명:
1. 주어진 초를 10초로 나눌 수 없는 경우 -1를 출력하고 종료
2. 300초, 60초, 10초 순으로 주어진 초를 줄여나가는 식으로 처리 (초 > 버튼일 때 Math.floor(초 / 버튼)하여 answer에 추가)
- 문제 링크: https://www.acmicpc.net/problem/1213
- 풀이 여부: Y
- 설명:
가운데 들어갈 문자열은 1개이거나 없어야 하고
그외 문자열은 최소 2개 이상, 짝수 개여야 팰린드롬이 성립
위 조건을 생각하여
문자열을  sort하고 [0], [1]번을 비교하여 같으면 answer의 양끝에서 비어있는 곳을 채워나가는 식으로 처리,
가운데 들어갈 문자열이 1개 이상이면 "I'm Sorry Hansoo" 출력
정상적으로 반복문이 종료되면 가운데 문자열을 채우고 join하여 출력
---
개인 문제는 1주차에  @soonba이 푸셨던 [팰린드롬 만들기] 문제 입니다!
어려운 문제 선행하여 풀어주신 @soonba 님께 감사드립니다! 🙇‍♀️🙇‍♀️🙇‍♀️

[Perlpark] 2주차 문제 제출

---

sykim/boj_11047.js
sykim/boj_9012.js

- 문제 링크: https://www.acmicpc.net/problem/11047
- 풀이 여부: Y
- 설명: 주어진 값 K를 동전의 가치가 큰 순서대로 나누어서 K가 0이 될 때까지 K를 깎아나가는 식으로 풀이. Greedy라는 분류를 알고 있다면 어렵지 않은 문제!
- 문제 링크: https://www.acmicpc.net/problem/9012
- 풀이 여부: Y
- 설명: 주어진 문자열이 올바른 괄호 문자열(VPS)을 포함하지 않을 때까지 ()를 정규식으로 지워나가, 최종으로 남는 것이 있다면 VPS가 아니므로 NO를, 남는 것이 없다면 YES를 출력.

[Sykim] 2주차 문제 제출

---

Kimyerim1935/프로그래머스_42862
soonba/boj_1005.java
soonba/boj_1541.java

- 문제 링크: https://www.acmicpc.net/problem/1541
- 풀이 여부: Y
- 설명 : 처음에 괄호를 적절히 사이사이에 넣고 계산하는 식으로 푸는건가 싶었지만, 난이도가 실버2라서 에이 설마 그렇게까지 어렵겠어 하고 명확한 규칙을 찾아보려고 노력했습니다. 메서드 분리하여 함수형으로 풀고자 했습니다. 마지막 식 계산하는 부분은 좀 더 깔끔한 방법이 있을 것 같은데 고민하고 있습니다.
- 문제 링크: https://www.acmicpc.net/problem/1005
- 풀이 여부: Y
- 설명 : 
(계기) 백준 사이트 처음 들어간 날에 언젠가 이런문제도 풀겠지 하면서 봤던 문제라 도전해봤습니다.
(해결 방식)처음엔 dfs 문제인 줄 알고 
클래스기반 OOP + dfs로 풀고자 건물(building), 건물들(buildings), 건설자(builder), 게임(ACMCraft) 등으로 객체지향 설계하였으나
시간복잡도 초과하였습니다. 알고리즘 바꿀 생각은 못하고 객체지향으로 풀다보니 과도한(불필요한) 시,공간 복잡도 차지하여 초과하는 줄로 예상하고 객체지향 틀을 유지한 채 리팩토링 했지만 6시간동안 성과 없이 끝나서 결국 알고리즘 분류를 보았습니다. DP + dfs 형태로 풀었습니다.
(어려웠던 부분)
지금까지 풀던 DP와 다르게 선형적인 식이 도출되지 않아 어려웠습니다. 결국 dfs로 깊이우선 탐색을 하면서 각 건물별 DP 값을 세팅해서
해당 건물을 짓는데 필요한 건물들을 List(N), 해당 건물 짓는 시간을 Time(N) 이라고 할 때, 대략적인 식은
DP[N] = Max( …

[soonba] 2주차 문제 제출

---

Kimyerim1935/프로그래머스_42862
steven/greedy/leetcode_122.go
steven/main.go
steven/math/leetcode_9.go

- 문제 링크: https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/
- 풀이 여부: Y
- 설명: 주식 가격 배열이 주어졌을 때, 최대 이익을 구하는 문제입니다. 문제를 처음 봤을 때는 복잡해 보였으나 규칙을 바탕으로 단순화하니 쉽게 풀 수 있었습니다. 아래는 Example 1인데 결국 오늘과 내일의 가격을 비교해 내일의 가격이 더 높을 때 내일 가격에서 오늘 가격을 뺀 이익을 더하는 방식으로 해결할 수 있습니다.
```
Input: prices = [7,1,5,3,6,4]
Output: 7
Explanation: Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3.
Total profit is 4 + 3 = 7.
```
- 문제 링크: https://leetcode.com/problems/palindrome-number/
- 풀이 여부: Y
- 설명: 숫자를 palindrome인지 확인하는 문제입니다.

[Steven] 2주차 문제 제출

---

hyoguoo/boj_13164.java
hyoguoo/boj_17836.java

- 문제 링크: https://www.acmicpc.net/problem/13164
- 풀이 여부: Y
- 설명
영역을 나누었을 때 해당 영역 내에 차이를 가장 적게 만드는 문제입니다(1,3,5,6,10 인 경우 1,3 / 5,6 / 10로 나눔)
하지만 굳이 영역을 실제로 나눌 필요 없이 세 개의 영역이 생기면 두 구간의 차이를 스킵할 수 있게 되는데,(위에서의 3-5, 6-10의 차이를 더하지 않아도 됨)
이 방식으로 접근해 키 차이 배열을 생성해 높은 값을 없애고 나머지를 더하는 방식으로 풀이했습니다.
처음에 절차적으로 아래와 같이 짜보았다가 당연히 시간초과가 발생했고 정렬 후 일부 구간만 더하는 풀이로 해결했습니다.
- 시간 초과 풀이
```java
private static int getMaximumDifferenceIndex(List<Integer> difference) {
int max = 0;
int index = 0;
for (int i = 0; i < difference.size(); i++) {
Integer value = difference.get(i);
if (value > max) {
max = value;
index = i;
}
}
return index;
}
private static void removeLargestValues(List<Integer> difference, int K) {
for (int i = 0; i < K - 1; i++) {
int maximumDifferenceIndex = getMaximumDifferenceIndex(difference); …
```

[hyoguoo] 2주차 문제 제출

---

Kimyerim1935/프로그래머스_42862.js
Kimyerim1935/프로그래머스_59036.sql

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42862
- 풀이 여부: Y
- 설명: 체육복을 빌려서 수업을 들을 수 있도록 도와주는 알고리즘
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/59036
- 풀이 여부: Y
- 설명: 아픈 동물의 아이디와 이름을 조회하는 sql문 작성

[Kimyerim1935] 2주차 문제 제출

---

soonba/boj_1017.java
soonba/boj_1106.java

- 문제 링크: https://www.acmicpc.net/problem/1027
- 풀이 여부: Y
- 설명: 선긋고 방정식을 세워 모든 경우의수를 대입해보는 Brute Force로 어렵지 않게 풀었습니다
- 문제 링크: https://www.acmicpc.net/problem/1106
- 풀이 여부: Y
- 설명: 전형적인 배낭문제입니다. 점화식은 46번라인입니다.
궁금한 것은 DP 업데이트를 최소값이므로 Math.min()으로 하고자 Arrays.fill() 메서드를 사용했는데 이런식으로 하는게 맞는지가 고민입니다. 왜냐면 [도시별 고객수의 최솟값]보다 작은 고객들의 DP 값 업데이트를 위해 43번라인을 추가했기 때문입니다..
43번라인이 없이는 [도시별 고객수의 최솟값] 보다 작은 DP는 Integer.MAX_VALUE 인채로 업데이트가 안 될 거라 점화식에서 overflow가 났습니다.  최선의 방법을 고민하고 있습니다..

[Soonba] 3주차 문제 제출

---

hyoguoo/boj_12919.java
hyoguoo/boj_2470.java

- 문제 링크: https://www.acmicpc.net/problem/12919
- 풀이 여부: Y
- 설명
문자열을 특정 규칙으로 목적 문자열로 만들 수 있는지에 대한 문제입니다.
처음에는 첫 번째 문자열에서 문자를 추가해 두 번째 문자열로 만들 수 있는지의 방법으로 접근했으나 시간 초과가 발생하여 문자를 소거하는 방식으로 접근하여 풀이할 수 있었습니다.
첫 번째 문자열을 S, 두 번째 문자열을 T라고 했을 때
S 문자열에서 T로 만드는 과정(문자를 추가하는 방법)에서 두 규칙 모두 적용하여 무작위로 재귀가 호출되며 새로운 문자열로 시도하게 되지만
T 문자열에서 S로 가는 과정(문자를 제거하는 방법)은 현재 문자열의 상태에 따라(마지막 문자가 A or 첫 번째 문자가 B) 재귀를 호출하기 때문에 호출 횟수가 비약적으로 감소할 수 있습니다!
- 문제 링크: https://www.acmicpc.net/problem/2470
- 풀이 여부: Y
- 설명
입력 받은 값을 오름차순으로 정렬 시킨 뒤 값이 적은 경우 왼쪽 인덱스를 올리고, 값이 큰 경우엔 오른쪽 인덱스를 줄이는 방식의 투포인터 문제입니다~

[hyoguoo] 3주차 문제 제출

---

steven/main.go
steven/math/leetcode_7.go
steven/sort/programmers_카펫.go

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42842?language=go
- 풀이 여부: Y
- 설명: 카펫의 갈색 격자의 수 brown, 노란색 격자의 수 yellow가 매개변수로 주어질 때 카펫의 가로, 세로 크기를 순서대로 배열에 담아 return하는 함수를 작성한다.
```go
* 세 가지 조건
1번째 조건: 세로 길이(sum % i)가 정수여야 한다.
2번째 조건: 가로 길이 + 세로 길이가 brown 타일의 갯수 / 2 + 2와 같아야 한다.
3번째 조건: 가로 길이가 세로 길이보다 길거나 같아야 한다.
```
- 문제 링크: https://leetcode.com/problems/reverse-integer/
- 풀이 여부: Y
- 설명: 수를 뒤집은 다음 출력하는 문제이다. 
```go
고민 되었던 부분
x 값이 양수인지 음수인지 확인한다. 양수면 "p", 음수면 "n"으로 표시했다.
sign := "p"
if x < 0 {
sign = "n"
}
마지막에 음수라면 결과 값에 -1을 곱한 다음 출력했다.
if sign == "n" {
res = res * -1
}
x 값은 해당 범위 안이라고 할지라도 뒤집은 수가 해당 값을 벗어날 수 있다. ex) 1534236469
if math.Pow(float64(2), float64(31))-1 < float64(res) || math.Pow(float64(2), float64(31))*-1 > float64(res) {
return 0
}
이런 식으로 마지막에서 예외 처리를 …
```

[Steven] 3주차 문제 제출

---

namiein/boj_2422.js
namiein/boj_2798.js

- 문제 링크: https://www.acmicpc.net/problem/2422
- 풀이 여부: Y
- 설명
섞어먹어도 되는 아이스크림 조합의 합 구하기.
- 문제 링크: https://www.acmicpc.net/problem/2798
- 풀이 여부: Y
- 설명
M을 넘지 않으면서 M에 최대한 가까운 카드 3장의 합 구하기.

[namiein] 3주차 문제 제출

---

perlpark/boj_17202.js
perlpark/boj_2748.js

- 문제 링크: https://www.acmicpc.net/problem/17202
- 풀이 여부: Y
- 설명: 두 개의 휴대폰 번호를 한 숫자씩 번갈아 더하여 2자리 수가 되면 출력하는 문제. 번호를 더하여 뒷자리(-1) 수만 새로운 배열에 담고, 만들어진 새로운 배열을 다시 test 배열로 바꿔 2자리 수가 될 때까지 반복하였음
- 문제 링크: https://www.acmicpc.net/problem/2748
- 풀이 여부: Y
- 설명: 피보나치 수열 연습 문제. a=0, b=1에서 시작하여 a=b, b=c(=a+b)를 반복하여 더하여 n 번째 더한 수를 출력함. n의 범위가 90까지여서 큰 수가 되어버리므로 0, 1을 BigInt로 만들어서 시작함

[Perlpark] 4주차 문제 제출

---

steven/dp/leetcode_22.go
steven/main.go
steven/stack/leetcode_20.go

- 문제 링크: https://leetcode.com/problems/generate-parentheses/description/
- 풀이 여부: N
- 설명: Dynamic Programming은 역시 어렵군요.. 
아래는 풀이를 이해하기 위해 사용한 툴입니다. 유용하니 참고해주세요!
- Tutor: https://pythontutor.com/visualize.html#mode=edit
아직 사용해보지 않으신 분들은 꼭 사용해보세요!
- chatGPT: https://chat.openai.com/ 
- 문제 링크: https://leetcode.com/problems/valid-parentheses/
- 풀이 여부: Y
- 설명: Open brackets must be closed by the same type of brackets(요약). Go는 for문 안에서 문자열을 아스키 코드로 출력한다. 이를 문자열로 받기 위해서는 string으로 감싸주어야 한다.

[Steven] 4주차 문제 제출

---

hyoguoo/boj_16235.java
hyoguoo/boj_2293.java

- 문제 링크: https://www.acmicpc.net/problem/2293
- 풀이 여부: Y
- 설명
coin list에 대한 반복문을 먼저하는 것이 핵심이었습니다! 그렇게 하지 않으면 목표 금액을 달성하기 위해 사용한 코인 순서들을 다른 것으로 취급하여 경우의 수를 더하게 되므로
한 코인에 대해 모든 경우의 수를 더하고, 더해진 상태에서 다음 코인에 대해 반복문을 수행하여 풀이를 할 수 있었습니다.
- 문제 링크: https://www.acmicpc.net/problem/16235
- 풀이 여부: Y
- 설명
문제의 지시대로 차근차근 구현하면 크게 어려운 문제는 아니지만 시간복잡도 측면에서 문제가 발생하여 이에 주의를 하며 구현해야 합니다!
해당 문제에서 핵심은 나무 나이가 낮은 순으로 정렬이 되어 있어야하는 것인데, 처음엔 ArrayList를 사용하여 정렬이 필요한 상태 직전에 정렬을 하였으나 시간초과가 발생하였습니다.
이를 해결하기 위해 우선순위큐를 사용하였으나 오히려 삽입과 삭제 시 정렬이 계속 발생하여 백준 책점기에서 더 이른 시간에 시간 초과가 발생하였구
Deque와 임시로 담아 둘 여러 자료구조 변수들을 사용하여 논리적으로 항상 정렬된 상태를 유지하는 것이 핵심이었습니다!

[hyoguoo] 4주차 문제 제출

---

sykim/boj_1010.js
sykim/boj_1463.js

- 문제 링크: https://www.acmicpc.net/problem/1463
- 풀이 여부: Y
- 설명: 1을 빼는 경우, 2로 나누는 경우, 3으로 나누는 경우에 대한 점화식을 전부 세워서 세 값 중 가장 작은 수를 구하는 문제. 푸는 방법만 깨달으면 풀이 자체는 얼마 안 걸리는 문제였습니다!
- 문제 링크: https://www.acmicpc.net/problem/1010
- 풀이 여부: Y
- 설명: DP문제긴한데 조합을 이용해서 풀었습니다. DP 이용한 풀이 봤는데 납득이 가진 않더라구요...

[Sykim] 4주차 문제 제출

---

Kimyerim1935/프로그래머스_151136.sql
Kimyerim1935/프로그래머스_42895.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42895
- 풀이 여부: Y
- 설명: 문제 유형이 익숙하지 않아서, 여러 사람들의 코드를 보면서 이해해보려고 노력했습니다 :) 하지만 여전히 어렵네요🥹
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/151136
- 풀이 여부: Y
- 설명: 종류가 SUV인 자동차들의 평균 일일 대여 요금을 구하는 sql문을 작성해봤습니다

[Kimyerim1935] 4주차 문제 제출

---

soonba/boj_1229.java
soonba/boj_1260.java

- 문제 링크: https://www.acmicpc.net/problem/1229
- 풀이 여부: Y
- 설명 : 0-1 배낭문제가 '주어진 아이템의' 무게(w)와 가치(v)로 최대 가치를 갖는 조합을 찾는 문제라면 
이 문제는 무게(w)는 모두 1로 고정인데 아이템을 내가 만들어야 하는 문제였습니다..
- 우선 목표 N에 대해 육각수(= 가치(v))를 초기화하면서 N보다 클 때 까지의 육각수를 구했습니다.
- 이후 DP로 풀었습니다. 다만 문제에서 힌트로 주어진
```
1791보다 큰 정수는 항상 육각수 4개의 합으로 만들 수 있다. 또한, 수가 충분히 크다면 항상 육각수 3개의 합으로 만들 수 있다. 또, 최소 개수는 항상 6 이하이고, 이것이 최소인 N은 11과 26밖에 없다. 답이 6인 가장 큰 N은 26, 5인 가장 큰 N은 130, 4인 가장 큰 N은 146858이다.
```
이부분이 걸려서 시간초과 날 것을 예상했는데.. 그냥 통과해서 저런 힌트는 왜 준거지? 싶었습니다. 다른 풀이를 봐도 좀 난해하네요.
- 문제 링크: https://www.acmicpc.net/problem/1260
- 풀이 여부: Y
- 설명 : BFS와 DFS 를 더 익히고싶어서 도전했습니다. BFS는 Queue로 해결하고 DFS는 재귀호출로 해결하였습니다. 기본적인 개념을 알게된 좋은 경험이었습니다. **BFS, DFS 공부를 아직 안하신 스터디분들께 이 문제를 추천합니다!!**

[Soonba] 4주차 문제제출

---

perlpark/boj_1260.js
perlpark/boj_2606.js

- 문제 링크: https://www.acmicpc.net/problem/1260
- 풀이 여부: Y
- 설명: DFS와 BFS의 기본 로직을 짜보는 문제. 효승님이 올려주신 강의를 참고하여 개념을 이해한 뒤 제 나름대로 초안을 써봤는데 영 아니어서 로직도 자바스크립트 버전으로 참고하여 작성했습니다. 그래프를 생성할 때 간선이 없는 정점이라고해서 blank/undefined를 두면 탐색할 때 어떤 케이스에서는 오류가 날 수 있기 때문에 처음에 정점 개수 만큼 false로 채운 N*N 배열을 만들었습니다. 질문 게시판에 반례 모음집이 있으니 이 문제에 도전하시는 분들은 참고하시면 좋을 거 같아요~
- 문제 링크: https://www.acmicpc.net/problem/2606
- 풀이 여부: Y
- 설명: 그래프를 탐색하여 시작점과 연결된 정점의 개수를 찾는 문제. DFS와 BFS에 썼던 BFS 로직에서 방문 여부를 체크하는 배열을 이용해 출력

[Perlpark] 5주차 문제 제출 

---

soonba/boj_11403.java
soonba/boj_2178.java

- 문제 링크: https://www.acmicpc.net/problem/2178
- 풀이 여부: Y
- 설명 : 감이 도저히 안 잡혀서 결국 접근 방식까지 보고 풀었습니다. 이해하고나니 어렵진 않아서 다음엔 더 잘 풀 수 있을 것 같습니다..전에 @hyoguoo  님이 인접행렬로 하신대서 인접행렬로 풀려고 해봤습니다. 변수선언이 과도하게 많나 싶어 고민하고있습니다.
- 문제 링크: https://www.acmicpc.net/problem/11403
- 풀이 여부: Y
- 설명 : 처음에 인접행렬로 구현하다가 61번 라인에서 해당 노드가 가진 모든 노드 탐색에서 최대 100번 무의미한 순회를 할 것 같아서 다시 중간에 리스트로 바꾸어 모든 점에 대해 bfs로 풀었습니다. 이렇게 해놓고 나니 공통 문제처럼 다음 노드가 ```다음 칸```과 같은 인접한 또는 일정한 규칙일 경우 행렬의 인덱스로 푸는 것이 좋은 것 같고 이 문제처럼 노드별 간선이 규칙없이 생긴 경우는 리스트로 순회하는 것이 효율적인 것 같네요. (딱 size 만큼만 돌테니...)
- 추가로 다른분들 풀이를 보니 이 문제가 ```플로이드 와샬```  문제라는데 관심있는 분은 보셔도 좋을 것 같습니다. (전 과하다 생각해서 안하겠습니다..)

[Soonba] 5주차 문제 제출

---

Kimyerim1935/프로그래머스_151138.sql
Kimyerim1935/프로그래머스_49189.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/49189
- 풀이 여부: N
- 설명: 그래프에 대한 이해가 높지 않아서 개념 정리에 초점을 맞춰 공부를 했습니다 
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/151138
- 풀이 여부: Y
- 설명: 조건에 따른 값을 판별하여 컬럼에 추가하는 sql 문을 작성하였습니다. 재밌더라구요

[Kimyerim1935] 5주차 문제 제출

---

sykim/boj_1018.js
sykim/boj_2606.js

- 문제 링크: https://www.acmicpc.net/problem/2606
- 풀이 여부: Y
- 설명: 1번 컴퓨터와 연결된 컴퓨터의 수를 찾는 문제였습니다. 그래프 처음 풀어봤는데 감이 안 잡혀서 이것저것 참고해서 풀었네요... 대강 이해는 했는데 여전히 반쯤은 이해를 못한거 같기도 하구...😂 새로 알게된 사실은 `array.map(item => Number(item))` 과 `array.map(Number)`가 같다는 것이었습니다...
- 문제 링크: https://www.acmicpc.net/problem/1018
- 풀이 여부: Y
- 설명: 정상인 체스판 두개(흰색 시작, 검은색 시작)를 만들어두고 입력된 판을 잘라 비교하는 문제였습니다. 처음에 문제가 잘 이해가 안돼서 해석에 애를 먹을 것 말고는 어렵지 않았습니다!

[Sykim] 5주차 문제 제출

---

hyoguoo/boj_11660.java
hyoguoo/boj_2194.java

- 문제 링크: https://www.acmicpc.net/problem/2194
- 풀이 여부: Y
- 설명
일반적인 BFS 최단 경로 찾기 문제에 유닛 크기가 추가 된 문제입니다. 해당 유닛의 크기만큼 방문 노드마다 2중 for문으로 추가적으로 검사하게 되는데 추가적으로 탐색하는 부분은 맵 범위 내에 존재하거나 벽이 없는 경우만 검색(방문 체크 X)하는게 핵심입니다.
- 문제 링크: https://www.acmicpc.net/problem/11660
- 풀이 여부: Y
- 설명
DP 문제 중 구간합 구하는 문제입니다. 2차원 배열의 경우 머릿속에 잘 안 그려져서 어려운 것 같네요.. getSum 부분은 아래 그림을 구한 것이라고 보면 됩니다!
[출처](https://nahwasa.com/entry/누적-합prefix-sum-2차원-누적합prefix-sum-of-matrix-with-java)

[hyoguoo] 5주차 문제 제출

---

steven/graph/leetcode_207.go
steven/graph/leetcode_997.go
steven/main.go

- 문제 링크: https://leetcode.com/problems/find-center-of-star-graph/
- 풀이 여부: Y
- 설명: 연결되어 있는 노드 중에서 중심 노드를 찾는 문제.
- 문제 링크: https://leetcode.com/problems/find-the-town-judge/
- 풀이 여부: Y
- 설명: 다른 누구도 믿지 않으면서 모두가 믿는 사람을 찾는 문제.

[Steven] 5주차 문제 제출

---

namiein/boj_2164.js
namiein/boj_2606.js

- 문제 링크: https://www.acmicpc.net/problem/2606
- 풀이 여부: Y
- 설명
1번 컴퓨터를 통해 웜 바이러스에 걸리게 되는 컴퓨터의 수 구하기 :)
- 문제 링크: https://www.acmicpc.net/problem/2164
- 풀이 여부: Y
- 설명
제일 마지막에 남게 되는 카드 구하기 :)

[namiein] 5주차 문제 제출

---

soonba/boj_1759.java
soonba/boj_7576.java

- 문제 링크: https://www.acmicpc.net/problem/1759
- 풀이 여부: Y
- 설명 : 난이도에 비해(?) 굉장히 고전했습니다.. 알고리즘 분류 최상위가 수학이라 도전했지만 딱히 수학인지는 모르겠네요. 사전식으로 가능성 있는 암호를 모두 출력하는 문제이고 저는 DFS로 풀었습니다. 기존 DFS를 완전 개념을 익힌 상태에서 도전한게 아니다보니, 해왔던 방식대로 풀다가 결국 다 풀고 리팩토링 하는 과정에서 불필요 코드를 많이 개선했습니다. DFS 중 스킵하는 조건이 까다로웠습니다.
- 문제 링크: https://www.acmicpc.net/problem/7576
- 풀이 여부: Y
- 설명 : 토마토가 다 익을때까지 날짜를 세는 문제입니다. 기존대비 특이점은
1. 여러 노드가 스타트지점인 BFS
2. 끝까지 방문하지 않는 노드를 체크해야함
정도 있었습니다. 
1은 startNodeList를 초기화하여 해결하였습니다.
2는 처음엔 0인 리스트 만들어서 list.remove() 했지만 시간복잡도가 초과하여, 아래와 같이 마지막에 2중 포문을 돌았습니다.
시간초과를 생각하여 리스트로 시도한건데, 2중포문이 더 빠른게 신기했던 문제였어요.

[Soonba] 6주차 문제 제출

---

perlpark/boj_14720.js
perlpark/boj_2292.js

- 문제 링크: https://www.acmicpc.net/problem/2292
- 풀이 여부: Y
- 설명: 계차수열을 알고 접근하니 더 쉽게 풀 수 있었던 문제였습니다. 반복문을 쓰지 않고 식을 세워서 풀 수도 있다는데, 식을 세우기가 저한테는 너무 어렵더라구요.. 주어진 시간이 2초로 넉넉했기 때문에 반복문을 사용했습니다. 처음에는 주어진 수 n까지 반복문을 돌려서 계산했는데, 시간이 4568 ms나 걸렸습니다. 계차수열임을 알고 수정하니까 172 ms로 줄었습니다.
- 문제 링크: https://www.acmicpc.net/problem/14720
- 풀이 여부: Y
- 설명: 어떤 수 % n은 0 ~ n-1까지의 숫자가 반복된다는 성질을 이용하여 우유를 먹어야 하는 순서에 맞을 때 count하는 방식으로 풀었습니다.

[Perlpark] 6주차 문제 제출

---

sykim/boj_1213.js
sykim/boj_1629.js

- 문제 링크: https://www.acmicpc.net/problem/1629
- 풀이 여부: Y
- 설명: 잘 안 풀려서 아이디어만 검색해서 이용했습니다. 모듈러 연산의 곱셈 성질과 재귀함수를 이용해 연산량을 줄이는게 핵심이었습니다! 다만 이것 말고 다른 방법이 있을 지 추후 조금 더 고민해보려고 합니다..
- 
- 문제 링크: https://www.acmicpc.net/problem/1213
- 풀이 여부: Y
- 설명: 팰린드롬 문제 저도 한번 풀어봤습니당! 이미 푸신 분들과 다른 방법을 써보려고 노력했습니다😄

[Sykim] 6주차 문제 제출

---

hyoguoo/boj_11444.java
hyoguoo/boj_1967.java

- 문제 링크: https://www.acmicpc.net/problem/11444
- 풀이 여부: Y
- 설명
피보나치 수열을 동적계획법 방식이 아니라 행렬을 이용해 푸는 방법입니다. 처음 보는 방법이라 신기해서 가져와봤어요..! 아래 참고 링크 확인하시면 피보나치수열을 행렬 표현으로 유도하는 방법이 잘 설명되어있는데 관심있으시면 읽어보면 좋을 것 같아요!
[참고](https://st-lab.tistory.com/252)
- 문제 링크: https://www.acmicpc.net/problem/1967
- 풀이 여부: Y
- 설명
모든 정점에 대해 거리 가중치를 더하면서 DFS를 돌려 풀 수 있었습니다!

[hyoguoo] 6주차 문제 제출

---

Kimyerim1935/프로그래머스_131112.sql
Kimyerim1935/프로그래머스_77884.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/77884
- 풀이 여부: Y
- 설명: 약수 개수를 판별하여 answer를 리턴하는 문제
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131112
- 풀이 여부: Y
- 설명: 특정 조건에 따른 sql문 작성

[Kimyerim1935] 6주차 문제 제출

---

steven/main.go
steven/math/leetcode_202.go
steven/sort/leetcode_35.go

- 문제 링크: https://leetcode.com/problems/happy-number/description/
- 풀이 여부: Y
- 설명: 계산이 끝없이 반복될 경우에 unhappy한 number가 되는데, 똑같은 값이 한번이라도 나온다면 반드시 반복된다는 점을 활용해야 한다.
- 문제 링크: https://leetcode.com/problems/search-insert-position/
- 풀이 여부: Y
- 설명: 전형적인 Binary Search 문제입니다. 문제에서 다음과 같이 전제 조건이 주어집니다. 
```
You must write an algorithm with O(log n) runtime complexity.
```

[Steven] 6주차 문제 제출

---

namiein/boj_1747.js
namiein/boj_9613.js

- 문제 링크: https://www.acmicpc.net/problem/1747
- 풀이 여부: Y
- 설명
소수이면서 팰린드롬인 수 중에서, 가장 작은 수 구하기.
처음에 Max 값의 조건을 잘못 이해해서 틀렸습니다....
- 문제 링크: https://www.acmicpc.net/problem/9613
- 풀이 여부: Y
- 설명
모든 쌍의 GCD의 합 구하기.

[namiein] 6주차 문제 제출

---

hyoguoo/boj_1916.java
hyoguoo/boj_2493.java

- 문제 링크: https://www.acmicpc.net/problem/2493
- 풀이 여부: Y
- 설명
숫자 배열이 주어지고 현재 인덱스보다 앞의 배열 중 큰 숫자의 인덱스(가장 가까운)를 찾는 문제입니다.
단순 이중 반복문을 사용하면 시간초과가 발생하기 때문에 스택을 이용해 불필요한 숫자를 지워나가면서 순회해야하는 문제였습니다
- 문제 링크: https://www.acmicpc.net/problem/1916
- 풀이 여부: Y
- 설명
일반적인 최단거리 탐색 알고리즘에서 가중치가 추가 된 문제입니다. 실제 지도에서 최단 거리를 찾는 것과 동일하게 생각하면 됩니다!
아래 글이 처음 보고 이해하기 좋더라구요
[다익스트라 알고리즘](https://blog.naver.com/ndb796/221234424646)

[hyoguoo] 7주차 문제 제출

---

soonba/boj_1780.java
soonba/boj_2812.java

- 문제 링크: https://www.acmicpc.net/problem/2812
- 풀이 여부: N
- 설명 : ```O(n)``` 으로 풀어야 했던 너무 어려웠던 문제입니다. 처음엔 매 자릿수에 대해 가능한 범위에서 (예를들어 첫번째 숫자는 0번 부터 (총 길이 - 지울수있는 길이) 의 인덱스 까지가 대상번호가 될 수 있으므로 각 자릿수 안에서 최적의 값을 가져오는 식으로 했으나 O(n^2)으로 메모리초과 시간초과 등등 이슈가 있었습니다. 결국 알고리즘 분류 보기를 넘어 풀이 방식까지 힌트를 얻어서 구현했습니다.
2중 for문 -> stack -> 마지막에 출력을 위해 reverse() 를 해야 함..? -> deque 로 개선
- 문제 링크: https://www.acmicpc.net/problem/1780
- 풀이 여부: Y
- 설명 : 분할과 정복문제로 머리아팠습니당. 처음엔 어레이를 복사하여 진행했는데, 메모리초과가 나서 고민 끝에 static으로 초기화 하여 해결했습니다.

[Soonba] 7주차 문제 제출

---

Kimyerim1935/프로그래머스_12906.js
Kimyerim1935/프로그래머스_59403.sql

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/12906
- 풀이 여부: Y
- 설명: filter 함수를 사용해서 중복되는 숫자를 제거했습니다.
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/59403
- 풀이 여부: Y
- 설명: 모든 동물의 아이디와 이름을 조회하는 쿼리문을 작성했습니다

[Kimyerim1935] 7주차 문제 제출

---

sykim/boj_24431.js
sykim/boj_4949.js

- 문제 링크: https://www.acmicpc.net/problem/4949
- 풀이 여부: Y
- 설명: 주어진 문자열에서 괄호만 뽑아내 쌍을 찾아주는 단순한 문제였습니다! 진주님이랑 같은 문제를 풀었네용ㅎㅎ
- 문제 링크: https://www.acmicpc.net/problem/24431
- 풀이 여부: Y
- 설명: 같은 접미사를 공유하는 단어들을 잘 묶기만 하면 해결할 수 있는 문제였습니다! 다음주에는 조금 더 어려운 문제에 도전해보는 것으로...

[Sykim] 7주차 문제 제출

---

steven/array/leetcode_26.go
steven/main.go
steven/stack/leetcode_225.go

- 문제 링크: https://leetcode.com/problems/implement-stack-using-queues/
- 풀이 여부: Y
- 설명: 2개의 Queue를 가지고 Stack을 구현하는 문제.
- 문제 링크: https://leetcode.com/problems/remove-duplicates-from-sorted-array/
- 풀이 여부: Y
- 설명: 기존 배열의 중복된 값을 제거한 배열 길이를 구하는 문제. 길이만 구한다면 굳이 배열을 생성하지 않아도 되지만 문제에서 요구하는 사항으로 인해 배열을 생성해 구현.

[Steven] 7주차 문제 제출

---

perlpark/boj_15649.js
perlpark/boj_15650.js

- 문제 링크: https://www.acmicpc.net/problem/15649
- 풀이 여부: Y
- 설명: 백트래킹 알고리즘 강의를 참고하여 기본 로직을 구현해 풀었습니다.
- 문제 링크: https://www.acmicpc.net/problem/15650
- 풀이 여부: Y
- 설명: 공통 문제에서 작성한 백트래킹 기본 로직에서 스코프마다 isUsed 상태 값을 갖게하여 상위 스코프에서 이미 처리한 값 + 현재 스코프에서 처리한 값을 참고하여 중복을 제거했습니다.

[Perlpark] 8주차 문제 제출

---

namiein/boj_15649.js
namiein/boj_15650.js

- 문제 링크: https://www.acmicpc.net/problem/15649
- 풀이 여부: Y
- 설명
DFS... 아직도 헷갈려서 힘드네요...😢 풀이 및 알고리즘 설명 참고하면서 풀었습니다.....
- 문제 링크: https://www.acmicpc.net/problem/15650
- 풀이 여부: Y
- 설명
백트래킹 계속 연습하려고 N과 M 시리즈 2번째 문제를 풀었습니다. 12번까지 있는 것 같아서 다 풀어보려고 합니당.

[namiein] 8주차 문제 제출

---

steven/dp/leetcode_39.go
steven/main.go
steven/string/leetcode_125.go

- 문제 링크: https://leetcode.com/problems/combination-sum/
- 풀이 여부: Y
- 설명: 전형적인 backtracking 문제입니다.
- 문제 링크: https://leetcode.com/problems/valid-palindrome/description/
- 풀이 여부: Y
- 설명: 문자열이 Palindrome인지 확인하는 문제입니다. 문자열에 포함된 특수문자를 정제하는 과정이 약간의 챌린지였습니다.

[Steven] 8주차 문제 제출

---

sykim/boj_15649.js
sykim/boj_4673.js

- 문제 링크: https://www.acmicpc.net/problem/15649
- 풀이 여부: Y
- 설명: dfs를 사용하여 풀이했습니다. dfs 백트래킹의 방법 중 하나라고 소개되어있기는 했는데 아직 개념을 정확하게 잡진 못한것 같아요;ㅅ;
- 문제 링크: https://www.acmicpc.net/problem/4673
- 풀이 여부: Y
- 설명: 완전 탐색을 써야한다고 생각한 뒤로도 방법을 생각하는데에 조금 시간이 걸렸습니다. 어쩐지 더 쉬운 방법이 있을 것 같은 예감이 드네요...

[Sykim] 8주차 문제 제출

---

hyoguoo/boj_11779.java
hyoguoo/boj_2448.java

- 문제 링크: https://www.acmicpc.net/problem/2580
- 풀이 여부: Y
- 설명
백트래킹 대표 문제인 스도쿠 문제입니다. 빈 칸들을 차례대로 1~9까지 넣어보면서(가능한 경우에만) 다음 칸으로 이동하게 되는데, 만약 입력할 수 없게 된다면 앞서 입력된 부분으로 돌아가 다음 경우의 수를 대입해보는 방식입니다.
- 문제 링크: https://www.acmicpc.net/problem/11779
- 풀이 여부: Y
- 설명
다익스트라 알고리즘을 수행하면서 지나온 정점을 출력해주는 문제로, 기존 비용만 저장하던 배열 대신 비용+지나온정점을 저장하는 클래스로 구현하여 풀 수 있었습니다.

[hyoguoo] 8주차 문제 제출

---

soonba/boj_1182.java
soonba/boj_1389.java

- 문제 링크: https://www.acmicpc.net/problem/1182
- 풀이 여부: Y
- 설명 : 처음에 일반적인 dfs로 풀고, 백트래킹이라는 주제에 맞게 검색하다보니 영감을 얻어 리팩토링하였습니다. 백트래킹을 아직 공부하지 못해서 그런지 신기했습니다.. 수학적 사고는 기본인 것 같네요.
- 문제 링크: https://www.acmicpc.net/problem/1389
- 풀이 여부: Y
- 설명 : 세상 사람들은 모두 6단계 이내로 아는 사람이라는 ```케빈 베이컨의 6단계 법칙``` 을 구현하는 문제였습니다. 그냥 직관적으로 어렵지 않게 풀었습니다.

[Soonba] 8주차 문제 제출

---

Kimyerim1935/프로그래머스_120810.c
Kimyerim1935/프로그래머스_12952.c

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/12952
- 풀이 여부: N
- 설명:  문제를 풀지는 못했고 다른 사람의 코드를 이해하는 쪽으로 스터디를 했습니다.
- 문제 링크:  https://school.programmers.co.kr/learn/courses/30/lessons/120808?language=c
- 풀이 여부:  Y
- 설명:   두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return하는 문제

[Kimyerim1935] 8주차 문제 제출

---

perlpark/boj_2003.js
perlpark/프로그래머스_150370.js

- 문제 링크: https://www.acmicpc.net/problem/2003
- 풀이 여부: Y
- 설명: 투 포인터를 이용한 [특정한 합을 가지는 부분 연속 수열 찾기] 문제 입니다. https://butter-shower.tistory.com/226 를 참고하여 풀었습니다. do~while 문(코드 블럭2)을 사용해봤는데 시간이 너무 오래 걸리길래 while 문(코드 블럭1)로 변경했습니다.
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150370
- 풀이 여부: Y
- 설명: 카카오 코테 문제여서 해봤는데 약간 단순하게 푼 거 같네요 ㅜㅜ 좀 더 수학적으로 풀 수 있는 방법이 있을지 고민해 봐야겠습니다.

[Perlpark] 9주차 문제 제출

---

Kimyerim1935/프로그래머스_120826.c
Kimyerim1935/프로그래머스_67258.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/67258
- 풀이 여부: N
- 설명: gems 배열이 주어질 때 가장 짧은 구간을 리턴하는 문제인데 설명을 봐도 이해가 잘 안가서 몇 번 더 봐야할 것 같아요🥲🥲
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/120826?language=c
- 풀이 여부: Y
- 설명: 특정문자를 제거한 뒤 리턴하는 문제입니다.

[kimyerim1935] 9주차 제출

---

soonba/boj_1011.java
soonba/boj_1337.java

- 문제 링크: https://www.acmicpc.net/problem/1337
- 풀이 여부: Y
- 설명 : 백트래킹 개념이 부족해서 골랐는데, 제 풀이는 브루트포스 같은 느낌입니다. 백트래킹은 따로 공부해봐야할 것 같습니다.. 
- 문제 링크: https://www.acmicpc.net/problem/1011
- 풀이 여부: Y
- 설명 : 규칙 발견이 힘들었던 문제이지만, 발견하고나니 알고리즘 기술이 필요하지 않은 수학 문제였습니다. 주석에 설명해두었습니당.

[Soonba] 9주차 문제 제출

---

hyoguoo/boj_11054.java
hyoguoo/boj_17144.java

- 문제 링크: https://www.acmicpc.net/problem/17144
- 풀이 여부: Y
- 설명
단순 구현하는 문제이지만 의외로 저장해야할 값이 많아 까다로운 문제인데, 리스트와 2차원 배열을 둘 다 비효율적으로 사용하는 것 같아서 시간이나 메모리 초과가 날 줄 알았으나 일단 통과가 됐는데 개선의 여지가 굉장히 많은 코드인 것 같습니다..
- 문제 링크: https://www.acmicpc.net/problem/11054
- 풀이 여부: Y
- 설명
[LIS](https://chanhuiseok.github.io/posts/algo-49/) 알고리즘 응용 문제로 
증가하는 부분과 감소하는 부분을 합치면 문제에서 원하는 조건이 성립하게 되어 해당 방법을 사용했습니다

[hyoguoo] 10주차 문제 제출

---

Kimyerim1935/프로그래머스_133024.sql
Kimyerim1935/프로그래머스_87391.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/87391
- 풀이 여부: Y
- 설명: 2차원 정수 배열이 주어질 때 x행 y열에 도착하는 시작점의 개수 리턴(풀다가 에러나서 참고해서 풀었습니다)
- 문제 링크:  https://school.programmers.co.kr/learn/courses/30/lessons/133024
- 풀이 여부:  Y
- 설명: 조건에 따른 내림차순 오름차순 정렬

[Kimyerim1935] 10주차 문제 제출

---

sykim/boj_1026.js
sykim/boj_1316.js

- 문제 링크: https://www.acmicpc.net/problem/1316
- 풀이 여부: Y
- 설명: 이미 나왔던 알파벳이 다른 알파벳이 나온 후에 또 나오는지만 체크하면 되는 문제입니다!
- 문제 링크: https://www.acmicpc.net/problem/1026
- 풀이 여부: Y
- 설명: 처음에 좀 헤멨는데... 문제 조건을 어기더라도 풀기만 하면 되는 문제였더라고요? 실제 코테에서도 그렇다고 하니 문제 조건에 너무 연연하지 않기루...🧐

[Sykim] 10주차 문제 제출

---

perlpark/boj_2578.js
perlpark/프로그래머스_120912.js

- 문제 링크: https://www.acmicpc.net/problem/2578
- 풀이 여부: Y
- 설명: 빙고가 3줄 만들어졌을 떄 몇 회차인지 반환하는 문제. 빙고판에서 확인된 숫자는 null로 변경, 가로/세로/X자가 빈 칸으로만 이루어진 경우를 카운트하여, 3 이상일 때 i+1를 출력했습니다. 빙고 3줄이 가능한 최소 개수 12부터 빈 칸 검사를 수핸하도록 조건식을 넣었는데, i > 11일 때 오류가 나더라구요?! 그래서 i > 10으로 바꿨는데.. 11칸으로 빙고 3줄이 만들어지는 경우가 있을까요? 제가 뭔가 잘못 이해하고 있는 걸까요?!?
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/120912
- 풀이 여부: Y
- 설명: 배열에서 7의 개수를 찾아서 반환하는 문제. 배열을 join 하여 matchAll로 개수를 찾아서 반환했습니다.

[Perlpark] 10주차 문제 제출

---

hyoguoo/boj_16973.java
hyoguoo/programmers_42888.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888
- 풀이 여부: Y
- 설명
들어온 레코드에 대해 닉네임 갱신 단계 / 출력 단계 나누어 풀었습니다.
- 문제 링크: https://www.acmicpc.net/problem/16973
- 풀이 여부: Y
- 설명
전에 풀이한 문제와 유사한 문제인데, 직사각형 범위에 대해 전부 검사할 필요 없이(시간복잡도 문제 발생) 테두리만 검사하여 문제를 풀이 할 수 있었습니다

[hyoguoo] 11주차 문제 제출

---

Kimyerim1935/프로그래머스_42747.js
Kimyerim1935/프로그래머스_42888.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888?language=javascript
- 풀이 여부:  Y
- 설명: map 사용하여 풀어보았습니다
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42747
- 풀이 여부:  Y
- 설명: H-index 구하는 문제

[Kimyerim1935] 11주차 문제 제출

---

soonba/boj_11650.java
soonba/프로그래머스_11650.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888?language=java
- 풀이 여부: Y
- 설명 : 유저의 인덱스, 입장 퇴장 정보만 가지고 있다가, 마지막으로 업데이트된 유저의 이름을 출력하는 방식으로 접근하였습니다. 직관적으로 접근하다보니 절차적으로 풀었네용..
- 문제 링크: https://www.acmicpc.net/problem/11650
- 풀이 여부: Y
- 설명 : 단순 정렬문제입니다.. 어렵지 않게 풀었습니다.

[Soonba] 11주차 문제 제출

---

perlpark/boj_11021.py
perlpark/프로그래머스_42888.js
perlpark/프로그래머스_42888.py

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888
- 풀이 여부: Y
- 설명: 주어진 record를 채팅방 메세지로 변환하면서 id와 nickname을 저장,
메세지를 반환하면서 id를 nickname으로 바꿔줌
- 문제 링크: https://www.acmicpc.net/problem/11021
- 풀이 여부: Y
- 설명: enumerate를 이용하여 인덱스 값을 사용할 수 있는 반복문을 돌림
Case #문자와 인덱스, numbers에서 split 하여 얻은 a, b 값을 더하여 형식에 맞게 출력

[Perlpark] 11주차 문제 제출

---

steven/dp/leetcode_78.go
steven/implementation/programmers_47888.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888
- 풀이 여부: Y
- 설명
- 문제 링크: https://leetcode.com/problems/subsets/
- 풀이 여부: N
- 설명: 멱집합을 구하는 문제.

[Steven] 11주차 문제 제출

---

sykim/boj_1920.js
sykim/프로그래머스_92341.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/92341?language=javascript
- 풀이 여부: Y
- 설명: 
```
주어진 records를 차량 번호를 key로 in, out을 모아 temp 객체를 생성한다.
temp 객체의 keys(차량 번호)를 번호가 작은 순서대로 정렬하여 keys 배열을 선언한다.
keys 배열을 돌며, 차량이 들어온 시간과 나간 시간의 차이를 구해 fees의 요금 정보를 통해 차량 별 정산 요금을 산정한다.
산정된 요금을 answer에 push한 후 반환한다.
```
- 문제 링크: https://www.acmicpc.net/problem/1920
- 풀이 여부: Y
- 설명: 정석적으로 풀면 이분탐색을 이용하는 문제이지만 Set을 이용하면 간편하게 풀 수 있습니다. 메모리를 조금 더 많이 먹는 것 같긴 했는데 크게 차이 날 정도는 아니었습니당.
Set 사용
이분 탐색

[Sykim] 12주차 문제 제출

---

Kimyerim1935/프로그래머스_133025.sql
Kimyerim1935/프로그래머스_92341.js

- 문제 링크:  https://school.programmers.co.kr/learn/courses/30/lessons/92341
- 풀이 여부:  Y
- 설명: 풀다가 막혀서 풀이 참고 했습니다 :-<
- 문제 링크:  https://school.programmers.co.kr/learn/courses/30/lessons/133025
- 풀이 여부:  Y
- 설명: 오랜만에 sql 문제 풀어봤습니다 :-)

[Kimyerim1935] - 12주차 문제 제출

---

akffkdahffkdgo77/programmers_42888.js
akffkdahffkdgo77/programmers_92341.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/92341?language=javascript#
- 풀이 여부: Y
- 설명
자동차별 누적 주차 시간을 계산하는 부분에서 계속 오류가 나서 풀이 참고했습니다. 
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888?language=javascript#
- 풀이 여부: Y
- 설명
11주차 공통 문제인 오픈채팅방 문제를 풀었습니다.

[akffkdahffkdgo77] 12주차 문제 제출

---

soonba/boj_1238.java
soonba/프로그래머스_92341.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/92341
- 풀이 여부: Y
- 설명 : map 에 대해 부족한 부분을 학습할 수 있었던 좋은 기회였습니다.
- 문제 링크: https://www.acmicpc.net/problem/1238
- 풀이 여부: Y
- 설명 : 다익스트라 알고리즘에 대한 문제였습니다. 알고리즘 분류를 보지 않고 풀다가, 알고리즘 분류 보고 학습하고 풀었습니다.
- 제가 푼 방법은 모든 노드에 대해 모든 최소값을 갱신하는 O(n^2) 방법입니다. 
- 최적화할 경우 각 노드별로 파티 노드까지의 경로만 계산해도 되는데, 추후 해보려고 합니다.

[Soonba] 12주차 문제 제출

---

hyoguoo/boj_27958.java
hyoguoo/programmers_92341.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/92341
- 풀이 여부: Y
- 설명
차번호를 키 값으로 하여 Map 두 개를 사용해서 절차적으로 풀이했습니다.
최근 입차 시간과 누적 주차 시간을 저장시키고, 주차장에서 끝까지 나가지 않은 것들에 대해 23:59로 계산 시켜 누적 주차 시간을 더하는 방식으로 했습니다~
- 문제 링크: https://www.acmicpc.net/problem/27958
- 풀이 여부: Y
- 설명
입력의 크기가 매우 작기 때문에(최대 판의 크기 8, 총알 5발)이라 모든 경우의 수가 3만여개 밖에 안 되기 때문에 모든 경우의 수를 대입하여 풀이 할 수 있었습니다.
은근히 제약조건이 많아 (체력과 점수가 따로 존재하여 다음 발사 시에도 해당 정보를 가지고 있어야함) 생각보다 까다로운 문제였네요

[hyoguoo] 12주차 문제 제출

---

soonba/boj_11050.java
soonba/프로그래머스_150368.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150368
- 풀이 여부: Y
- 설명 : 이모티콘 개수가 최대 7개이고 할인율의 카테고리는 4개로 총 4^7(== 2^14)로 모든 이모티콘에 모든 할인율 경우의 수를 계산하는 DFS로 풀었습니다.
- 문제 링크: https://www.acmicpc.net/problem/11050
- 풀이 여부: Y
- 설명 : 조합 공식입니다. 최대 n이 10이지만, DP로 풀려고 했습니다.

[Soonba] 13주차 문제 제출

---

akffkdahffkdgo77/programmers_150368.js
akffkdahffkdgo77/programmers_178871.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150368
- 풀이 여부: Y
- 설명
문제가 이해가 안 돼서 풀이를 참고했습니다. 코드가 너무 길어서 함수로 분리해서 작성해봤습니다….
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/178871
- 풀이 여부: Y
- 설명
배열로 하면 시간초과 에러가 나서 hash를 사용해서 풀어야 하는 문제입니다.

[akffkdahffkdgo77] 13주차 문제 제출

---

steven/main.go
steven/string/leetcode_38.go

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150368
- 풀이 여부: N
- 설명: 시간을 조금 더 들여 풀어보겠습니다.
- 문제 링크: https://leetcode.com/problems/count-and-say/
- 풀이 여부: Y
- 설명: 처음에 내용 이해가 잘 되지 않습니다. 이 문제도 재귀를 활용해 풀었습니다.

[Steven] 13주차 문제 제출

---

hyoguoo/boj_18249.java
hyoguoo/programmers_150368.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150368
- 풀이 여부: Y
- 설명
모든 경우의 수를 탐색하여 최대값을 찾아서 풀었습니닷
- 문제 링크: https://www.acmicpc.net/problem/18429
- 풀이 여부: Y
- 설명
모든 경우의 수 탐색하여 백트래킹했습니당

[hyoguoo] 13주차 문제 제출

---

soonba/boj_11279.java
soonba/프로그래머스_150369.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150369
- 풀이 여부: Y
- 설명 Car 클래스만들고, Map사용해 풀다가 시간초과가 났습니다. 고민해보다가 처음에는 배송과 수거 index를 각각 업데이트하며 두 작업 모두 끝날 때까지 while을 실행하였는데, 다른 분들의 풀이를 보고 저장하여 다음 집에 넘기는 방식으로 변경하여 올렸습니다. ; (
- 문제 링크: https://www.acmicpc.net/problem/11279
- 풀이 여부: Y
- 설명 : PQ로 조건에 맞게 분기처리하여 간단히 풀었습니다... 문제 의도는 이게 아니었나 싶기도 한데 분류에는 우선순위 큐 라고 되어있긴합니다.

[Soonba] 14주차 문제 제출

---

hyoguoo/boj_3107.java
hyoguoo/programmers_150369.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150369
- 풀이 여부: Y
- 설명
배달/픽업 하나의 변수로만 풀이하려고 시도하다 시간이 많이 소요됐습니다.. 많이 어려웠네용
- 문제 링크: https://www.acmicpc.net/problem/3107
- 풀이 여부: Y
- 설명
문자열 처리 문제로 매 단계마다 데이터 처리하기 쉬운 형태로 변환하면서 풀이했습니다.
하나의 자료형으로 유지해서 풀면 더 효율적으로 풀이가 되지 않을까 싶네요

[hyoguoo] 14주차 문제 제출

---

steven/bit-manipulation/leetcode_191.go
steven/greedy/programmers_150369.go
steven/main.go

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150369?language=go
- 풀이 여부: Y
- 설명: 배달과 수거를 독립적으로 보는 것이 문제 해결에 도움되었습니다.
- 문제 링크: https://leetcode.com/problems/number-of-1-bits/
- 풀이 여부: Y
- 설명: 비트를 다루는 문제입니다.

[Steven] 14주차 문제 제출

---

perlpark/프로그래머스_150369.js
perlpark/프로그래머스_181950.py

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/150369
- 풀이 여부: N
- 설명: 테스트 케이스에선 되는데 제출이 안되네영 좀 더 고민해서 수정해 보겠습니다. ^-^
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/181950
- 풀이 여부: Y
- 설명: 문자열 반복. 파이썬은 문자열에 곱하기 연산이 되므로 간단히 풀 수 있는 문제였습니다.

[Perlpark] 14주차 문제 제출

---

soonba/bonus.java
soonba/프로그래머스_118667.java
soonba/프로그래머스_133924.sql

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/118667
- 풀이 여부: Y
- 설명 : 합이 int 범위보다 커질 수 있는 점을 간과했고, q1 + q2 에서 q1을 한 번 더 이어주는 과정에서 시간이 조금 걸렸습니다. 아이디어 자체는 어렵지 않았습니다.
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/133024
- 풀이 여부: Y
- 설명 :  order by에 대한 sql문제입니다.

[Soonba] 15주차 문제 제출

---

akffkdahffkdgo77/programmers_118667.js
akffkdahffkdgo77/programmers_176963.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/118667
- 풀이 여부: Y
- 설명
투 포인터 문제풀이 참고했습니다.
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/176963
- 풀이 여부: Y
- 설명
프로그래머스 레벨 1 문제 입니다.

[akffkdahffkdgo77] 15주차 문제 제출

---

hyoguoo/boj_1072.java
hyoguoo/programmers_118667.java

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/118667?language=java
- 풀이 여부: Y
- 설명
큐1에 대해 합을 절반과 비교해 넣고 빼고를 반복하여 풀이했습니다~
- 문제 링크: https://www.acmicpc.net/problem/1072
- 풀이 여부: Y
- 설명
이분탐색도 가능하지만 방정식을 이용해 풀이해봤습니다

[hyoguoo] 15주차 문제 제출

---

sykim/boj_2559.js
sykim/프로그래머스_118667.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/118667
- 풀이 여부: Y
- 설명: shift, push를 사용하면 당연히 시간초과가 날 것 같아서(실제로도 시간초과가 납니다 js살려) index를 사용해서 풀었습니다. 원래 queue1의 합계를 구할 때 for문을 돌려서 구해줬었는데 몇몇 케이스에서 시간초과가 나서 let으로 경우에 따라 더하고 뺴주는 식으로 구해줬습니다.
- 문제 링크: https://www.acmicpc.net/problem/2559
- 풀이 여부: Y
- 설명: 실버3 치고는 매우 쉬운 문제였습니다. 다만 최대값이 음수가 나올 수 있어서 `let max = 0`으로 설정하고 시작했더니 문제가 생겨서, for문을 돌 때 startIndex가 0인 경우 max에 초기값을 지정해주는 식으로 해결했습니다.

[Sykim] 15주차 문제 제출

---

steven/implementation/programmers_118667.js
steven/implementation/programmers_12946.js

- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/118667
- 풀이 여부: Y
- 설명: 2개의 queue를 연결해 two pointer 방식으로 풀었습니다.
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/12946
- 풀이 여부: Y
- 설명: 일반적인 하노이 문제입니다.

[Steven] 15주차 문제 제출
